[2025-01-28T23:45:02.312+0000] {processor.py:157} INFO - Started process (PID=160) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:45:02.314+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-01-28T23:45:02.316+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:45:02.315+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:45:02.530+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:45:02.485+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 4, in <module>
    from scripts.main import process_csv
ModuleNotFoundError: No module named 'scripts'
[2025-01-28T23:45:02.531+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:45:02.604+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.300 seconds
[2025-01-28T23:45:32.793+0000] {processor.py:157} INFO - Started process (PID=165) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:45:32.796+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-01-28T23:45:32.798+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:45:32.797+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:45:32.807+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:45:32.805+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 4, in <module>
    from scripts.main import process_csv
ModuleNotFoundError: No module named 'scripts'
[2025-01-28T23:45:32.808+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:45:32.871+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.088 seconds
[2025-01-28T23:46:02.962+0000] {processor.py:157} INFO - Started process (PID=170) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:46:03.012+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-01-28T23:46:03.013+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:46:03.013+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:46:03.019+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:46:03.018+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 4, in <module>
    from scripts.main import process_csv
ModuleNotFoundError: No module named 'scripts'
[2025-01-28T23:46:03.020+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:46:03.061+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.105 seconds
[2025-01-28T23:46:33.234+0000] {processor.py:157} INFO - Started process (PID=175) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:46:33.235+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-01-28T23:46:33.237+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:46:33.236+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:46:33.244+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:46:33.242+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 4, in <module>
    from scripts.main import process_csv
ModuleNotFoundError: No module named 'scripts'
[2025-01-28T23:46:33.245+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:46:33.293+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.067 seconds
[2025-01-28T23:47:03.435+0000] {processor.py:157} INFO - Started process (PID=180) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:47:03.503+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-01-28T23:47:03.505+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:47:03.504+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:47:03.512+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:47:03.510+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 4, in <module>
    from scripts.main import process_csv
ModuleNotFoundError: No module named 'scripts'
[2025-01-28T23:47:03.513+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:47:03.553+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.126 seconds
[2025-01-28T23:47:33.668+0000] {processor.py:157} INFO - Started process (PID=185) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:47:33.670+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-01-28T23:47:33.672+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:47:33.671+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:47:33.681+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:47:33.678+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 4, in <module>
    from scripts.main import process_csv
ModuleNotFoundError: No module named 'scripts'
[2025-01-28T23:47:33.681+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:47:33.721+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.060 seconds
[2025-01-28T23:48:03.928+0000] {processor.py:157} INFO - Started process (PID=190) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:48:03.960+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-01-28T23:48:03.962+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:48:03.961+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:48:03.974+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:48:03.968+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 4, in <module>
    from scripts.main import process_csv
ModuleNotFoundError: No module named 'scripts'
[2025-01-28T23:48:03.975+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:48:04.081+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.168 seconds
[2025-01-28T23:48:34.139+0000] {processor.py:157} INFO - Started process (PID=195) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:48:34.141+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-01-28T23:48:34.142+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:48:34.142+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:48:34.151+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:48:34.149+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 4, in <module>
    from scripts.main import process_csv
ModuleNotFoundError: No module named 'scripts'
[2025-01-28T23:48:34.151+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:48:34.197+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.065 seconds
[2025-01-28T23:49:04.320+0000] {processor.py:157} INFO - Started process (PID=200) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:49:04.357+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-01-28T23:49:04.359+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:49:04.358+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:49:04.366+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:49:04.365+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 4, in <module>
    from scripts.main import process_csv
ModuleNotFoundError: No module named 'scripts'
[2025-01-28T23:49:04.367+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:49:04.410+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.097 seconds
[2025-01-28T23:49:34.553+0000] {processor.py:157} INFO - Started process (PID=205) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:49:34.554+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-01-28T23:49:34.556+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:49:34.555+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:49:34.564+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:49:34.562+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 4, in <module>
    from scripts.main import process_csv
ModuleNotFoundError: No module named 'scripts'
[2025-01-28T23:49:34.564+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:49:34.601+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.053 seconds
[2025-01-28T23:51:56.587+0000] {processor.py:157} INFO - Started process (PID=158) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:51:56.603+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-01-28T23:51:56.605+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:51:56.604+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:51:56.617+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:51:56.610+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 4, in <module>
    from scripts.main import process_csv
ModuleNotFoundError: No module named 'scripts'
[2025-01-28T23:51:56.621+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:51:56.706+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.138 seconds
[2025-01-28T23:52:27.494+0000] {processor.py:157} INFO - Started process (PID=164) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:52:27.495+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-01-28T23:52:27.496+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:52:27.496+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:52:27.502+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:52:27.500+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 4, in <module>
    from scripts.main import process_csv
ModuleNotFoundError: No module named 'scripts'
[2025-01-28T23:52:27.502+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:52:27.549+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.060 seconds
[2025-01-28T23:52:57.664+0000] {processor.py:157} INFO - Started process (PID=169) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:52:57.676+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-01-28T23:52:57.677+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:52:57.677+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:52:57.683+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:52:57.681+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 4, in <module>
    from scripts.main import process_csv
ModuleNotFoundError: No module named 'scripts'
[2025-01-28T23:52:57.683+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:52:57.736+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.078 seconds
[2025-01-28T23:56:05.978+0000] {processor.py:157} INFO - Started process (PID=159) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:56:05.997+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-01-28T23:56:06.003+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:56:06.002+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:56:06.025+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:56:06.023+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 4, in <module>
    from scripts.main import process_csv
ModuleNotFoundError: No module named 'scripts'
[2025-01-28T23:56:06.050+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:56:06.188+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.240 seconds
[2025-01-28T23:56:36.988+0000] {processor.py:157} INFO - Started process (PID=165) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:56:36.990+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-01-28T23:56:36.992+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:56:36.991+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:56:36.999+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:56:36.997+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 4, in <module>
    from scripts.main import process_csv
ModuleNotFoundError: No module named 'scripts'
[2025-01-28T23:56:37.000+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:56:37.058+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.076 seconds
[2025-01-28T23:57:07.230+0000] {processor.py:157} INFO - Started process (PID=170) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:57:07.265+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-01-28T23:57:07.266+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:57:07.266+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:57:07.272+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:57:07.271+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 4, in <module>
    from scripts.main import process_csv
ModuleNotFoundError: No module named 'scripts'
[2025-01-28T23:57:07.272+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:57:07.311+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.088 seconds
[2025-01-28T23:57:37.415+0000] {processor.py:157} INFO - Started process (PID=175) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:57:37.416+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-01-28T23:57:37.417+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:57:37.417+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:57:37.423+0000] {logging_mixin.py:150} INFO - [2025-01-28T23:57:37.422+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 4, in <module>
    from scripts.main import process_csv
ModuleNotFoundError: No module named 'scripts'
[2025-01-28T23:57:37.424+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-01-28T23:57:37.462+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.052 seconds
